#!/usr/bin/env zsh

# source core file
for file ($(ls ${ZDOTDIR}/core)) {
    source "${ZDOTDIR}/core/${file}"
}

zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "Aloxaf/fzf-tab"

#zsh_apply_theme
command -v starship &> /dev/null && eval "$(starship init zsh)"

# display system info
command -v neofetch &> /dev/null && clear && neofetch

# fzf setup
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh ] && source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh
