#!/usr/bin/env zsh

HISTSIZE=10000
SAVEHIST=10000

EDITOR="nvim"

export LC_ALL="en_US.UTF-8"
export XDG_CONFIG_HOME="${HOME}/.config"
export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/starship.toml"
PATH="$PATH:$HOME/.local/bin"
