#!/usr/bin/env zsh

HISTSIZE=10000
SAVEHIST=10000

EDITOR="nvim"

# Language
export LC_ALL="en_US.UTF-8"

# XDG define
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CACHE_HOME="${HOME}/.cache"

# package config define
## starship
export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/starship.toml"

# PATH env
PATH="$PATH:$HOME/.local/bin"
