#!/usr/bin/env zsh

HISTSIZE=10000
SAVEHIST=10000

EDITOR="nvim"

# Language
export LC_ALL="en_US.UTF-8"

# XDG define
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

# package config define
## zsh
export HISTFILE="${XDG_STATE_HOME}/zsh/history"
## go
export GOPATH="${XDG_DATA_HOME}/go"
## starship
export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/starship.toml"

# PATH env
PATH="$PATH:$HOME/.local/bin"
