#!/usr/bin/env zsh

function zsh_add_file(){
	[ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1"
}

function zsh_add_plugin(){
	PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
	[ ! -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ] && git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$PLUGIN_NAME"
	zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
	zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
}

